<?php

/**
 * @file
 * Primary module hooks for User Management API module.
 */

/**
 * Implements hook_mail().
 */
function user_management_api_mail($key, &$message, $params) {
  switch ($key) {
    case 'verify_email':
      $message['headers']['Content-Type'] = 'text/plain; charset=UTF-8; format=flowed; delsp=yes';
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }
}
